### ISSUE TITLE
Parser fails with 'TypeError' on invalid query "a^"

### ISSUE THREAD

**Issue by ygavenchuk** [jurismarches/luqum#70]
During parsing an invalid query like `a^` the parser fails with `TypeError: conversion from NoneType to Decimal is not supported` 

<pre>
Traceback (most recent call last):
  File "scratches/scratch1.py", line 12, in <module>
    qb = parser.parse('a^')
  File "lib/python3.8/site-packages/ply/yacc.py", line 333, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "lib/python3.8/site-packages/ply/yacc.py", line 1120, in parseopt_notrack
    p.callable(pslice)
  File "lib/python3.8/site-packages/luqum/parser.py", line 316, in p_boosting
    p[0] = Boost(p[1], p[2].value)
  File "lib/python3.8/site-packages/luqum/tree.py", line 374, in __init__
    self.force = Decimal(force).normalize()
TypeError: conversion from NoneType to Decimal is not supported
</pre>

Expected result: `luqum.exceptions.ParseSyntaxError: Syntax error in input ...`

**Comment by alexgarel** [comment]
It's true that the parser is not doing all the checks it could be doing, and  that's kind of a tedious work to do ! But we can at least fix this.

**Comment by alexgarel** [comment]
I re-read the [lucene documentation](https://lucene.apache.org/core/2_9_4/queryparsersyntax.html) and indeed Boost can be implicite (defaults to 1).
I implemented it in a PR.
